// Shared recovery and setup controls are available from every operational screen.
(function(){
 let rendering=false;
 async function draw(){if(rendering||!Ops.state)return;rendering=true;try{
  let panel=document.getElementById('opsRecovery');if(panel?.contains(document.activeElement)&&['INPUT','SELECT'].includes(document.activeElement.tagName))return;if(!panel){panel=document.createElement('details');panel.id='opsRecovery';panel.style.cssText='position:fixed;bottom:8px;right:8px;z-index:10050;max-width:420px;width:calc(100% - 32px);max-height:65vh;overflow:auto;background:white;color:#172339;border:1px solid #aab;border-radius:10px;padding:10px;font:14px system-ui;box-shadow:0 3px 12px #0003';document.body.append(panel)}
  const pending=await Ops.pending(),s=Ops.state;const summary=document.createElement('summary');summary.textContent='Operations · '+pending.length+' pending sync'+(Ops.state._offline?' | OFFLINE, cached state':'');const content=document.createElement('div');const oldOpen=panel.open;panel.replaceChildren(summary,content);panel.open=oldOpen;
  const message=document.createElement('p');message.setAttribute('role','status');content.append(message);
  function button(label,action){const b=document.createElement('button');b.type='button';b.textContent=label;b.style.cssText='margin:5px;padding:8px';b.onclick=async()=>{b.disabled=true;try{await action();message.textContent='Saved';await Ops.refresh();await draw()}catch(e){message.textContent=e.message}finally{b.disabled=false}};content.append(b);return b}
  function form(title,fields,action){const f=document.createElement('form');const h=document.createElement('h4');h.textContent=title;f.append(h);for(const [name,label,type] of fields){const input=document.createElement('input');input.name=name;input.placeholder=label;input.type=type||'text';input.required=true;input.style.cssText='display:block;margin:5px;width:90%;padding:8px';f.append(input)}const submit=document.createElement('button');submit.textContent=title;f.append(submit);f.onsubmit=async e=>{e.preventDefault();submit.disabled=true;try{await action(Object.fromEntries(new FormData(f)));await Ops.refresh();await draw()}catch(err){message.textContent=err.message}finally{submit.disabled=false}};content.append(f)}
  button('Retry pending sync',()=>Ops.retry());for(const p of pending){const row=document.createElement('p');row.textContent=(p.request.kind||p.request.action)+': '+(p.error||'Awaiting acknowledgment');content.append(row)}
  if(s.role!=='driver'){
   const select=document.createElement('select');select.setAttribute('aria-label','Warehouse');for(const w of s.warehouses){const option=document.createElement('option');option.value=w.id;option.textContent=w.name+' — '+w.address;select.append(option)}select.value=localStorage.getItem('tp_warehouse_'+s.organization.id)||s.warehouses[0]?.id||'';select.onchange=()=>localStorage.setItem('tp_warehouse_'+s.organization.id,select.value);content.append(select);
   button('Import manifest',()=>{const input=document.createElement('input');input.type='file';input.accept='.csv,text/csv';input.onchange=async()=>{if(!input.files[0])return;try{if(!select.value)throw Error('Configure a warehouse first');message.textContent='Processing manifest...';await Ops.importManifest(await input.files[0].text(),select.value);await draw()}catch(e){message.textContent=e.message}};input.click()});
   button('Print package labels',()=>Ops.labels());
   for(const m of s.manifests.filter(m=>m.status!=='published'||s.packages.some(p=>p.manifest_id===m.id&&p.exception_code==='geocode_failed'))){button('Resume manifest '+m.id.slice(0,8),async()=>{let result=await Ops.api({action:'resume',manifest_id:m.id});while(result.more)result=await Ops.api({action:'resume',manifest_id:m.id})})}
   for(const row of s.rows.filter(row=>row.error||s.packages.some(p=>p.row_id===row.id&&['geocode_failed','identity_conflict'].includes(p.exception_code)))){const info=document.createElement('p');info.textContent='Row '+row.row_number+': '+(row.error||s.packages.find(p=>p.row_id===row.id&&p.exception_code)?.exception_code)+' · '+(row.raw.address||'No address');content.append(info);if(!row.error||row.error==='missing_address')form('Correct address for row '+row.row_number,[['address','Full delivery address']],v=>Ops.command('correct_address',{row_id:row.id,address:v.address}))}
   form('Hold package',[['code','Scan package barcode'],['reason','Reason for hold']],v=>Ops.command('hold',v));
   form('Acknowledge physical return',[['code','Scan package barcode']],v=>Ops.command('return_package',v));
   if(s.role==='dispatcher'){form('Add warehouse',[['name','Warehouse name'],['address','Physical pickup address']],v=>Ops.command('warehouse',v));form('Add physical bin',[['label','Physical bin label']],v=>Ops.command('bin',{...v,warehouse_id:select.value}));form('Register driver',[['name','Driver name'],['phone','Driver phone','tel']],v=>Ops.command('register_driver',v))}
  }
 }finally{rendering=false}}
 Ops.onChange(()=>draw().catch(console.error));
})();
