import test from 'node:test';import assert from 'node:assert/strict';import {chromium} from '@playwright/test';import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import {randomUUID,createHash} from 'node:crypto';import {database} from './database.mjs';
test('signed-in browser lifecycle uses persisted package custody across all apps',{timeout:60000},async t=>{
 const db=await database();t.after(()=>db.close());const org=randomUUID(),driver=randomUUID();await db.query('insert into organizations(id,name) values($1,$2)',[org,'Browser test']);await db.query('insert into drivers(id,org_id,name,phone) values($1,$2,$3,$4)',[driver,org,'Test Driver','5550001234']);const sessions={};for(const role of ['dispatcher','warehouse','driver']){const token=randomUUID();const actor=role==='driver'?driver:org;sessions[role]={token,org:{id:org},actor_id:actor,role};await db.query('select ops_create_session($1,$2,$3,$4)',[org,actor,role,createHash('sha256').update(token).digest('hex')])}
 const cmd=async(kind,payload,role='dispatcher',id=randomUUID())=>(await db.query('select ops_command($1,$2,$3,$4) as result',[sessions[role].token,id,kind,payload])).rows[0].result;
 const state=async(role='dispatcher')=>(await db.query('select ops_state($1) as result',[sessions[role].token])).rows[0].result;
 const warehouse=(await cmd('warehouse',{name:'Warehouse',address:'100 Warehouse Way'})).warehouse_id;await cmd('bin',{warehouse_id:warehouse,label:'1A'});
 const manifest=(await cmd('intake',{warehouse_id:warehouse,source:'test',external_id:'browser',content_hash:'browser',raw_text:'test',rows:[{row_number:1,order_id:'0001',recipient:'Recipient',address:'1 Main Street',packages:2},{row_number:2,order_id:'0002',recipient:'Return',address:'2 Main Street',packages:1}]})).manifest_id;
 let s=await state();for(const row of s.rows)await cmd('geocode',{row_id:row.id,lat:33.7,lng:-84.3});await cmd('publish',{manifest_id:manifest,routes:[{key:'browser',rows:s.rows.map(r=>r.id)}]});
 const parent=path.resolve(import.meta.dirname,'../..');const root=fs.existsSync(path.join(parent,'dispatcher.html'))?parent:path.join(parent,'tackpath-app');const server=http.createServer((req,res)=>{try{const file=path.join(root,new URL(req.url,'http://localhost').pathname);res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':'text/html');res.end(fs.readFileSync(file))}catch{res.statusCode=404;res.end()}});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>server.close());
 const browser=await chromium.launch({channel:'chrome',headless:true});t.after(()=>browser.close());const errors=[];let proofFailures=1,apiOffline=false;
 async function page(file,role){const context=await browser.newContext({serviceWorkers:'block'});await context.addInitScript(session=>localStorage.setItem('tp_ops_session',JSON.stringify(session)),sessions[role]);await context.route('https://hofijsiphyjpdvujjzfi.supabase.co/**',async route=>{const req=route.request();if(apiOffline)return route.abort('internetdisconnected');if(!req.url().includes('/functions/v1/ops-api'))return route.fulfill({status:200,body:'[]',contentType:'application/json'});try{const b=req.postDataJSON();let result;if(b.action==='state')result=await state(role);else if(b.action==='command')result=await cmd(b.kind,b.payload,role,b.id);else if(b.action==='proof_upload'){if(proofFailures-->0)throw Object.assign(Error('Injected storage outage'),{status:503});await db.query('select ops_proof_uploaded($1,$2,$3)',[sessions[role].token,b.proof_id,(await state(role)).proofs.find(p=>p.id===b.proof_id).content_hash]);result={uploaded:true}}else if(b.action==='legacy')result=[];else throw Error('Unhandled action '+b.action);await route.fulfill({status:200,body:JSON.stringify(result),contentType:'application/json'})}catch(e){await route.fulfill({status:e.status||409,body:JSON.stringify({error:e.message}),contentType:'application/json'})}});const page=await context.newPage();page.on('pageerror',e=>errors.push(file+': '+e.stack));await page.goto('http://127.0.0.1:'+server.address().port+'/'+file);await page.waitForFunction(()=>window.Ops?.state);return page}
 const dispatch=await page('dispatcher.html','dispatcher');await dispatch.evaluate(()=>loadJobs());assert.match(await dispatch.locator('#opsAccounting').innerText(),/3 expected/);
 const stow=await page('stow.html','warehouse');s=await state();for(const p of s.packages){await stow.evaluate(code=>handleStowScan(code),p.barcode);await stow.evaluate(()=>handleStowScan('1A'))}assert.equal((await state()).packages.filter(p=>p.state==='stowed').length,3);
 const popupPromise=dispatch.waitForEvent('popup');await dispatch.evaluate(()=>Ops.labels());const labels=await popupPromise;await labels.waitForFunction(()=>document.querySelectorAll('svg rect').length>0,null,{timeout:5000}).catch(async e=>{console.log('LABEL DIAGNOSTIC',await labels.evaluate(()=>({base:document.baseURI,body:document.body.innerHTML,barcode:typeof JsBarcode})));throw e});assert.equal(await labels.locator('svg').count(),3);await labels.close();
 const route=(await state()).routes[0];await dispatch.evaluate(id=>openDrawer(id),route.id);await dispatch.locator('#assignDriverSelect').selectOption(driver);await dispatch.getByRole('button',{name:'Assign driver',exact:true}).click();await dispatch.waitForFunction(()=>Ops.state.routes.some(r=>r.driver_id),null,{timeout:5000}).catch(async e=>{console.log('ASSIGN DIAGNOSTIC',await dispatch.evaluate(()=>({selection:document.getElementById('assignDriverSelect')?.value,toasts:document.body.innerText.slice(-3000),assign:assignJobToDriver.toString()})),errors);throw e});const drive=await page('driver-app.html','driver');await drive.evaluate(()=>opsDriverSync());for(const p of s.packages)await drive.evaluate(code=>processScan(code),p.barcode);await drive.evaluate(()=>confirmSurgeLoad());assert.equal((await state()).routes[0].status,'in_transit');
 await drive.evaluate(()=>{openSurgePOD();podTab='photo';podPhotoData=document.createElement('canvas').toDataURL('image/png');document.getElementById('podRecipient').value='Recipient'});await drive.evaluate(()=>submitPOD());assert.equal((await state()).deliveries.length,0);assert.equal(await drive.evaluate(async()=>(await Ops.pending()).length),1);await drive.reload();await drive.waitForFunction(()=>Ops.state?.deliveries.length===1);assert.equal((await state()).deliveries.length,1);assert.equal(await drive.evaluate(async()=>(await Ops.pending()).length),0);
 const remaining=(await state()).stops.find(s=>s.status==='pending');await dispatch.evaluate(id=>Ops.command('cancel_stop',{stop_id:id,reason:'Return test'}),remaining.id);await drive.evaluate(()=>startJobStatusPoll());assert.equal((await state()).routes[0].status,'reconciling');const held=(await state()).packages.find(p=>p.state==='held');await stow.evaluate(code=>Ops.command('return_package',{code}),held.barcode);await dispatch.evaluate(()=>loadJobs());await drive.evaluate(()=>startJobStatusPoll());s=await state();assert.equal(s.routes[0].status,'closed');assert.equal(s.accounting.delivered,2);assert.equal(s.accounting.returned_or_held,1);assert.equal(await drive.evaluate(()=>currentJob),null);apiOffline=true;await dispatch.evaluate(()=>Ops.refresh());assert.equal(await dispatch.evaluate(()=>Ops.state._offline),true);apiOffline=false;await dispatch.evaluate(()=>Ops.refresh());assert.equal(await dispatch.evaluate(()=>!!Ops.state._offline),false);assert.deepEqual(errors,[]);
});
