import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID,createHash} from 'node:crypto';
import {database} from './database.mjs';
const uuid=()=>randomUUID();
test('physical package lifecycle, conservation and injected failures',async t=>{
 const db=await database();t.after(()=>db.close());
 const org=uuid(),other=uuid(),driver=uuid(),driver2=uuid(),admin=uuid();
 const tokens={admin:'admin-'+uuid(),driver:'driver-'+uuid(),driver2:'driver2-'+uuid(),other:'other-'+uuid()};
 for(const id of [org,other])await db.query('insert into public.organizations(id,name) values($1,$2)',[id,'test']);
 for(const id of [driver,driver2])await db.query('insert into public.drivers(id,org_id,name) values($1,$2,$3)',[id,org,id]);
 for(const [key,token] of Object.entries(tokens))await db.query('select public.ops_create_session($1,$2,$3,$4)',[key==='other'?other:org,key==='driver'?driver:key==='driver2'?driver2:admin,key.startsWith('driver')?'driver':'dispatcher',createHash('sha256').update(token).digest('hex')]);
 const cmd=async(kind,payload={},who='admin',id=uuid())=>(await db.query('select public.ops_command($1,$2,$3,$4) as result',[tokens[who],id,kind,payload])).rows[0].result;
 const state=async(who='admin')=>(await db.query('select public.ops_state($1) as state',[tokens[who]])).rows[0].state;
 const warehouse=(await cmd('warehouse',{name:'test',address:'100 Warehouse Way'})).warehouse_id;
 await cmd('bin',{warehouse_id:warehouse,label:'1A'});await cmd('bin',{warehouse_id:warehouse,label:'2A'});
 const rows=[{row_number:1,order_id:'ORDER-1',recipient:'A',address:'one',packages:2},{row_number:2,order_id:'ORDER-2',tracking_number:'TRACK-2',recipient:'B',address:'two',packages:1},{row_number:3,order_id:'ORDER-3',recipient:'C',address:'bad',packages:1},{row_number:4,order_id:'ORDER-4',recipient:'D',address:'four',packages:1}];
 const intake={warehouse_id:warehouse,source:'test',external_id:'manifest-1',content_hash:'hash-1',raw_text:'raw manifest',rows};
 const manifest=(await cmd('intake',intake)).manifest_id;
 await t.test('duplicate manifest creates no extra pieces',async()=>{assert.equal((await cmd('intake',intake)).duplicate,true);assert.equal((await state()).packages.length,5);await assert.rejects(cmd('intake',{...intake,content_hash:'different'}),/different content/)});
 const sourceRows=(await state()).rows.sort((a,b)=>a.row_number-b.row_number);
 for(const row of sourceRows)await cmd('geocode',{row_id:row.id,...(row.row_number===3?{error:'ZERO_RESULTS'}:{lat:33.7+row.row_number/100,lng:-84.3})});
 await t.test('failed geocode retains package with recoverable exception',async()=>{assert.equal((await state()).packages.filter(p=>p.exception_code==='geocode_failed').length,1)});
 const plan={manifest_id:manifest,routes:[{key:'a',rows:[sourceRows[0].id,sourceRows[1].id]},{key:'b',rows:[sourceRows[3].id]}]};
 await t.test('partial publication rolls back all routes and is retryable',async()=>{await assert.rejects(cmd('publish',{...plan,routes:[plan.routes[0],{key:'bad',rows:[uuid()]}]}));assert.equal((await state()).routes.length,0);await cmd('publish',plan);await cmd('publish',plan);assert.equal((await state()).routes.length,2)});
 let st=await state();let route=st.routes.find(r=>r.plan_key==='a');const route2=st.routes.find(r=>r.plan_key==='b');let bin=st.bins.find(b=>b.route_id===route.id);
 await t.test('occupied bin cannot be assigned to another route',async()=>{await assert.rejects(cmd('reserve_bin',{route_id:route2.id,bin:bin.label}),/occupied/)});
 const pieces=st.packages.filter(p=>p.route_id===route.id);const first=pieces[0];
 await t.test('wrong bin rejected without changing custody',async()=>{await assert.rejects(cmd('stow',{code:first.barcode,bin:'NOPE'}),/Wrong bin/);assert.equal((await state()).packages.find(p=>p.id===first.id).custody,'expected')});
 await t.test('database failure rolls back stow and retry succeeds',async()=>{
  await db.exec(`create function operations.test_failure() returns trigger language plpgsql as $$begin if new.kind='stow' then raise exception 'injected database failure';end if;return new;end$$;create trigger test_failure before insert on operations.commands for each row execute function operations.test_failure();`);
  const id=uuid();await assert.rejects(cmd('stow',{code:first.barcode,bin:bin.label},'admin',id),/injected/);assert.equal((await state()).packages.find(p=>p.id===first.id).state,'allocated');await db.exec('drop trigger test_failure on operations.commands');await cmd('stow',{code:first.barcode,bin:bin.label},'admin',id);
 });
 await t.test('duplicate and alias scans count one physical package',async()=>{const id=uuid(),payload={code:first.barcode,bin:bin.label};await cmd('stow',payload,'admin',id);await cmd('stow',payload,'admin',id);const aliased=pieces.find(p=>p.tracking_number==='TRACK-2');await cmd('stow',{code:'TRACK-2',bin:bin.label});await cmd('stow',{code:'ORDER-2',bin:bin.label});assert.equal((await state()).packages.filter(p=>p.state==='stowed').length,2)});
 await t.test('refresh/reconnect reads persisted counts and identities',async()=>{const a=await state(),b=await state();assert.deepEqual(a.packages,b.packages);assert.equal(a.bins.find(b=>b.id===bin.id).present,2)});
 for(const p of pieces)await cmd('stow',{code:p.barcode,bin:bin.label});
 await cmd('assign',{route_id:route.id,driver_id:driver});route=(await state()).routes.find(r=>r.id===route.id);
 await t.test('incomplete driver load blocks departure',async()=>{await assert.rejects(cmd('start',{route_id:route.id,version:route.version},'driver'),/Incomplete/)});
 const oldVersion=route.version;
 await t.test('reassignment invalidates previous driver and stale version',async()=>{await cmd('assign',{route_id:route.id,driver_id:driver2});await assert.rejects(cmd('load',{route_id:route.id,version:oldVersion,code:first.barcode},'driver'),/Assignment changed/);await cmd('assign',{route_id:route.id,driver_id:driver});route=(await state()).routes.find(r=>r.id===route.id)});
 for(const p of pieces)await cmd('load',{route_id:route.id,version:route.version,code:p.barcode},'driver');
 await t.test('loading transfers custody and releases empty bin',async()=>{const s=await state();assert.equal(s.bins.find(b=>b.id===bin.id).present,0);assert.equal(s.bins.find(b=>b.id===bin.id).route_id,null);assert.equal(s.packages.filter(p=>p.route_id===route.id&&p.driver_id===driver).length,3);await assert.rejects(cmd('assign',{route_id:route.id,driver_id:driver2}),/custody/)});
 await cmd('start',{route_id:route.id,version:route.version},'driver');
 const stops=(await state()).stops.filter(s=>s.route_id===route.id).sort((a,b)=>a.sequence-b.sequence);
 const proof=uuid();await cmd('proof_prepare',{route_id:route.id,version:route.version,stop_id:stops[0].id,proof_id:proof,kind:'photo',content_hash:'proofhash'},'driver');
 const delivery={route_id:route.id,version:route.version,stop_id:stops[0].id,proof_id:proof,recipient:'Recipient'};
 await t.test('failed POD upload prevents delivery',async()=>{await assert.rejects(cmd('deliver',delivery,'driver'),/Proof upload/);assert.equal((await state()).deliveries.length,0)});
 await db.query('select public.ops_proof_uploaded($1,$2,$3)',[tokens.driver,proof,'proofhash']);
 await t.test('failed final write leaves custody and evidence intact; retry is idempotent',async()=>{await db.exec(`create or replace function operations.test_failure() returns trigger language plpgsql as $$begin if new.kind='deliver' then raise exception 'injected final failure';end if;return new;end$$;create trigger test_failure before insert on operations.commands for each row execute function operations.test_failure();`);const id=uuid();await assert.rejects(cmd('deliver',delivery,'driver',id),/injected/);assert.equal((await state()).deliveries.length,0);assert.equal((await state()).packages.filter(p=>p.state==='delivered').length,0);await db.exec('drop trigger test_failure on operations.commands');await cmd('deliver',delivery,'driver',id);await cmd('deliver',delivery,'driver',id);assert.equal((await state()).deliveries.length,1)});
 await t.test('cancelled stop is held, not delivered; return reconciles custody',async()=>{await cmd('cancel_stop',{stop_id:stops[1].id,reason:'cancelled by customer'});let s=await state();assert.equal(s.stops.find(x=>x.id===stops[1].id).status,'cancelled');assert.equal(s.routes.find(x=>x.id===route.id).status,'reconciling');const p=s.packages.find(x=>x.stop_id===stops[1].id);await cmd('return_package',{code:p.barcode});assert.equal((await state()).routes.find(x=>x.id===route.id).status,'closed');assert.equal((await db.query('select status from public.jobs where id=$1',[route.id])).rows[0].status,'closed_with_exceptions')});
 await t.test('organization isolation enforced on reads and commands',async()=>{assert.equal((await state('other')).packages.length,0);await assert.rejects(cmd('assign',{route_id:route.id,driver_id:driver},'other'),/not found/);await assert.rejects(cmd('deliver',delivery,'admin'),/Driver authentication/)});
 await t.test('N=5 physical packages conserved with zero unexplained',async()=>{const a=(await state()).accounting;assert.equal(a.expected,5);assert.equal(a.recorded,5);assert.equal(a.delivered,2);assert.equal(a.returned_or_held,1);assert.equal(a.exceptions,2);assert.equal(a.active,0);assert.equal(a.unknown_quantity_rows,0);assert.equal(a.expected,a.delivered+a.returned_or_held+a.exceptions);console.log('CONSERVATION',JSON.stringify(a))});
});
